dataset:
  real_scenes_images_path: "/scratch/09076/dks2000/datasets/Image-Cartoonization/data/real_images/scenes/train"
  cartoon_scenes_images_path: "/scratch/09076/dks2000/datasets/Image-Cartoonization/data/cartoon_images/naruto_scenes"
  # real_scenes_images_path: "/home/krishna/Image-Cartoonization/data/real_images/scenes/train"
  # cartoon_scenes_images_path: "/home/krishna/Image-Cartoonization/data/cartoon_images/naruto_scenes"
  real_faces_images_path: "/scratch/09076/dks2000/datasets/Image-Cartoonization/data/real_images/faces/train"
  cartoon_faces_images_path: "/scratch/09076/dks2000/datasets/Image-Cartoonization/data/cartoon_images/naruto_faces"
  # real_faces_images_path: "/home/krishna/Image-Cartoonization/data/real_images/faces/train"
  # cartoon_faces_images_path: "/home/krishna/Image-Cartoonization/data/cartoon_images/naruto_faces"
  sample_steps: [4,1]
  batch_size: 64
  num_workers: 32
stage: "train"
load_ckpt_path:
pretrain_ckpt_path: "/work/09076/dks2000/ls6/Image-Cartoonization/checkpoints/best_pretrain_model.ckpt"
# pretrain_ckpt_path: "/home/krishna/Image-Cartoonization/checkpoints/best_pretrain_model.ckpt"
model:
  lambda_variation: 10000.0
  lambda_surface: 0.1
  lambda_texture: 1
  lambda_structure_content: 200
checkpoint:
  dirpath: "/work/09076/dks2000/ls6/Image-Cartoonization/checkpoints/naruto"
  # dirpath: "checkpoints/naruto"
  filename: "best_model"
  save_top_k: -1
  mode: "min"
trainer:
  num_nodes: 1
  gpus: 1
  max_epochs: 20
  val_check_interval: 250
  limit_val_batches: 1
  log_every_n_steps: 10